export const CLEAR_ERROR = "CLEAR_ERROR";

export const GET_USERS_REQUESTED = "GET_USERS_REQUESTED";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";

export const GET_TRANSCRIPTION_REQUEST = "GET_TRANSCRIPTION_REQUEST";
export const GET_TRANSCRIPTION_SUCCESS = "GET_TRANSCRIPTION_SUCCESS";
export const GET_TRANSCRIPTION_FAILED = "GET_TRANSCRIPTION_FAILED";

export const GET_TRANSLATION_REQUEST = "GET_TRANSLATION_REQUEST";
export const GET_TRANSLATION_SUCCESS = "GET_TRANSLATION_SUCCESS";
export const GET_TRANSLATION_FAILED = "GET_TRANSLATION_FAILED";

export const GET_COMPLEMENT_REQUEST = "GET_COMPLEMENT_REQUEST";
export const GET_COMPLEMENT_SUCCESS = "GET_COMPLEMENT_SUCCESS";
export const GET_COMPLEMENT_FAILED = "GET_COMPLEMENT_FAILED";

export const GET_FASTA_REQUEST = "GET_FASTA_REQUEST";
export const GET_FASTA_SUCCESS = "GET_FASTA_SUCCESS";
export const GET_FASTA_FAILED = "GET_FASTA_FAILED";

export const GET_BLAST_REQUEST = "GET_BLAST_REQUEST";
export const GET_BLAST_SUCCESS = "GET_BLAST_SUCCESS";
export const GET_BLAST_FAILED = "GET_BLAST_FAILED";
